import Head from "next/head";
import Header from "@/components/Index/Header";
import Projects from "@/components/Index/Projects/Projects";
import Intro from "@/components/Commons/Intro";
import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { useRouter } from "next/router";

export default function Home() {
  useEffect(() => {
    const test = () => {
      console.log("test");
      router.push("Projects")
    };
    document.addEventListener("scroll", test, true);

    return () => document.removeEventListener("scroll", test, true);
  }, []);
  const router = useRouter()
  return (
    <div className="h-[101vh] ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  );
}
